version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: orders-db-ms-api-goodfood
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - goodfood-network

  app:
    image: fernandesrh/orders-microsservice-api-goodfood:latest
    container_name: order-goodfood-app
    restart: always
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DATABASE}?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - goodfood-network

volumes:
  mysql-data:

networks:
  goodfood-network:
    driver: bridge